services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: task_manager
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: